user  nginx;
worker_processes  auto;

error_log  /usr/local/nginx/logs/error.log error;
pid        /usr/local/nginx/logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # define log format for JSON output, for elk stack
    log_format json_combined escape=json
    '{'
            '"ts": "$time_iso8601",'
            '"message": "handled request $request_method $request_uri",'
            '"request": {'
                '"id": "$http_x_request_id",'
                '"remote_ip": "$remote_addr",'
                '"remote_port": "$remote_port",'
                '"http_x_forwarded_for": "$http_x_forwarded_for",'
                '"protocol": "$server_protocol",'
                '"method": "$request_method",'
                '"host": "$host",'
                '"uri": "$request_uri",'
                '"headers": {'
                    '"user-agent": "$http_user_agent",'
                    '"accept": "$http_accept",'
                    '"accept-encoding": "$http_accept_encoding",'
                    '"accept_language: "$http_accept_language"'
                '}'
            '},'
            '"bytes_read": $request_length,'
            '"duration_msecs": $request_time,'
            '"size": $bytes_sent,'
            '"status": $status,'
            '"resp_headers": {'
            '"content_length": "$sent_http_content_length",'
            '"content_type": "$sent_http_content_type"'
            '}'
        '}';


    access_log    /usr/local/nginx/logs/access.log json_combined;

    sendfile        on;
    keepalive_timeout  65;

    # set security headers
    server_tokens off;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    server {
	listen       8080 default_server;

        # Healthcheck-Route ohne Logging
        location = /_health {
            access_log off;
            return 200 'OK';
            add_header Content-Type text/plain;
        }

        location / {
            root   /usr/local/nginx/html;
            index  index.html index.htm;
        }

        # deny access to hidden files
        location ~ /\. {
            deny all;
        }
    }
}
